name: Test Student Card Status Check

on:
  project_card:
    types: [created, deleted, moved]

jobs:
  check-project-card-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check Project Card Status
        run: |
          echo "Issue status changed"
