name: Issue Activity 2

on:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  issue-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger on Issue Activity
        run: |
          echo "An issue was updated or a comment was made"
